TravelWeb.Client/Controllers/AuthorController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using TravelWeb.Client.Extensions;
using TravelWeb.Client.Helpers;
using TravelWeb.Client.Models;
using TravelWeb.Client.Services;
using TravelWeb.Client.Settings;
using TravelWeb.Client.Wrappers;

namespace TravelWeb.Client.Controllers
{
    public class AuthorController : Controller
    {
        private readonly FunctionHelper _functionHelper;
        private readonly EndPointSetting _endpoint;

        public AuthorController(FunctionHelper functionHelper, IOptions<EndPointSetting> options)
        {
            _functionHelper = functionHelper;
            _endpoint = options.Value;
        }


        public async Task<ActionResult> Index()
        {
            var authors = await _functionHelper.GetPagedResponse<List<AuthorModel>>(_endpoint.TravelApi, _endpoint.AuthorUrl);
            return View(authors.Data);
        }

        public ActionResult Create()
        {
            return View(new CreateAuthorViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateAuthorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var token = HttpContext.Session.Get<string>("token");
                var result =
                    await _functionHelper.PostAuthorization<Response<int>, CreateAuthorViewModel>(_endpoint.TravelApi, _endpoint.AuthorUrl, token, model);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                ModelState.AddModelError("AuthorError", result.Message);
            }

            return View(model);
        }

    }
}

TravelWeb.Client/Controllers/EditorialController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using TravelWeb.Client.Extensions;
using TravelWeb.Client.Helpers;
using TravelWeb.Client.Models;
using TravelWeb.Client.Services;
using TravelWeb.Client.Settings;
using TravelWeb.Client.Wrappers;

namespace TravelWeb.Client.Controllers
{
    public class EditorialController : Controller
    {

        private readonly FunctionHelper _functionHelper;
        private readonly EndPointSetting _endpoint;

        public EditorialController(FunctionHelper functionHelper, IOptions<EndPointSetting> options)
        {
            _functionHelper = functionHelper;
            _endpoint = options.Value;
        }

        public async Task<ActionResult> Index()
        {
            var editorials = await _functionHelper.GetPagedResponse<List<EditorialModel>>(_endpoint.TravelApi, _endpoint.Editorial);
            return View(editorials.Data);
        }
        
        public ActionResult Create()
        {
            return View(new CreateEditorialViewModel());
        }

        [HttpPost] 
        public async Task<IActionResult> Create(CreateEditorialViewModel model)
        {
            if (ModelState.IsValid)
            {
                var token = HttpContext.Session.Get<string>("token");
                var result =
                    await _functionHelper.PostAuthorization<Response<int>, CreateEditorialViewModel>(_endpoint.TravelApi, _endpoint.Editorial, token,model);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                ModelState.AddModelError("EditorialError", result.Message);
            }

            return View(model);
        }

    }
}

TravelWeb.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TravelWeb.Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TravelWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Editorial" asp-action="Index">Editorial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TravelWeb.Client - Alberto Palencia Benedetty
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>